CREATE TABLE IF NOT EXISTS s_stroke_admit_death(
id varchar(32) NOT NULL,
hospcode varchar(5) NOT NULL,
areacode varchar(8) NOT NULL,
date_com varchar(14) DEFAULT NULL,
b_year varchar(4) NOT NULL,
targetq1 INTEGER DEFAULT 0,
targetq2 INTEGER DEFAULT 0,
targetq3 INTEGER DEFAULT 0,
targetq4 INTEGER DEFAULT 0,
resultq1 INTEGER DEFAULT 0,
resultq2 INTEGER DEFAULT 0,
resultq3 INTEGER DEFAULT 0,
resultq4 INTEGER DEFAULT 0,

target1_q1 INTEGER DEFAULT 0,
target2_q1 INTEGER DEFAULT 0,
target3_q1 INTEGER DEFAULT 0,

target1_q2 INTEGER DEFAULT 0,
target2_q2 INTEGER DEFAULT 0,
target3_q2 INTEGER DEFAULT 0,

target1_q3 INTEGER DEFAULT 0,
target2_q3 INTEGER DEFAULT 0,
target3_q3 INTEGER DEFAULT 0,

target1_q4 INTEGER DEFAULT 0,
target2_q4 INTEGER DEFAULT 0,
target3_q4 INTEGER DEFAULT 0,

result1_q1 INTEGER DEFAULT 0,
result2_q1 INTEGER DEFAULT 0,
result3_q1 INTEGER DEFAULT 0,

result1_q2 INTEGER DEFAULT 0,
result2_q2 INTEGER DEFAULT 0,
result3_q2 INTEGER DEFAULT 0,

result1_q3 INTEGER DEFAULT 0,
result2_q3 INTEGER DEFAULT 0,
result3_q3 INTEGER DEFAULT 0,

result1_q4 INTEGER DEFAULT 0,
result2_q4 INTEGER DEFAULT 0,
result3_q4 INTEGER DEFAULT 0
);