CREATE TABLE IF NOT EXISTS s_2q_anc(
id varchar(32) NOT NULL,
hospcode varchar(5) NOT NULL,
areacode varchar(8) NOT NULL,
date_com varchar(14) DEFAULT NULL,
b_year varchar(4) NOT NULL,
target INTEGER DEFAULT 0,
result INTEGER DEFAULT 0,

b INTEGER DEFAULT 0,
a INTEGER DEFAULT 0,

b1b140 INTEGER DEFAULT 0,
b1b141 INTEGER DEFAULT 0,
a1b140 INTEGER DEFAULT 0,
a1b141 INTEGER DEFAULT 0
);