CREATE TABLE IF NOT EXISTS s_ht_screen_follow(
id varchar(32) NOT NULL,
hospcode varchar(5) NOT NULL,
areacode varchar(8) NOT NULL,
date_com varchar(14) DEFAULT NULL,
b_year varchar(4) NOT NULL,
target INTEGER DEFAULT 0,
result INTEGER DEFAULT 0,
r1 INTEGER DEFAULT 0,
r2 INTEGER DEFAULT 0,

t_q1 INTEGER DEFAULT 0,
r_q1 INTEGER DEFAULT 0,
r1_q1 INTEGER DEFAULT 0,
r2_q1 INTEGER DEFAULT 0,

t_q2 INTEGER DEFAULT 0,
r_q2 INTEGER DEFAULT 0,
r1_q2 INTEGER DEFAULT 0,
r2_q2 INTEGER DEFAULT 0,

t_q3 INTEGER DEFAULT 0,
r_q3 INTEGER DEFAULT 0,
r1_q3 INTEGER DEFAULT 0,
r2_q3 INTEGER DEFAULT 0,

t_q4 INTEGER DEFAULT 0,
r_q4 INTEGER DEFAULT 0,
r1_q4 INTEGER DEFAULT 0,
r2_q4 INTEGER DEFAULT 0,

target_13 INTEGER,
result_13 INTEGER,
r_home_bp_13 INTEGER,
r_hosp_bp_13 INTEGER,
non_follow90_13 INTEGER,
over90 INTEGER
);