CREATE TABLE IF NOT EXISTS s_ncd_screen_repleate1 (
id VARCHAR(32) NOT NULL,
hospcode VARCHAR(5) NOT NULL,
areacode VARCHAR(8) NOT NULL,
date_com VARCHAR(14),
b_year VARCHAR(4) NOT NULL,
targetq1 INTEGER,
targetq2 INTEGER,
targetq3 INTEGER,
targetq4 INTEGER,
resultq1 INTEGER,
resultq2 INTEGER,
resultq3 INTEGER,
resultq4 INTEGER,
target INTEGER,
result INTEGER,
yymm VARCHAR(6) NOT NULL,
date_fz VARCHAR(14) NULL,
target_13 INTEGER,
result_13 INTEGER,
non_follow180_13 INTEGER,
over180 INTEGER
);